-- Add missing fields from API requirements
ALTER TABLE lands
ADD COLUMN IF NOT EXISTS is_recommendation BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS login_required BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS mls BOOLEAN DEFAULT FALSE;
