package com.landgo.coreservice.dto.response;
import com.landgo.coreservice.enums.LandStatus;
import com.landgo.coreservice.enums.ProjectStage;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.*;
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class LandResponse {
    private UUID id;
    private ProjectStage projectStage;
    private LandStatus status;
    private String address;
    private String city;
    private String postalCode;
    private BigDecimal lotSize;
    private String lotUnit;
    private String frontage;
    private String depth;
    private String currentZoningCodes;
    private String pinNumber;
    private String officialPlanDesignation;
    private BigDecimal latitude;
    private BigDecimal longitude;
    private Map<String, Object> projectSpecification;
    private BigDecimal askingPrice;
    private String currency;
    private String pricingDescription;
    private List<Map<String, String>> photos;
    private List<Map<String, String>> documents;
    private String ownershipVerification;
    private Integer viewCount;
    private Integer inquiryCount;
    private boolean isFeatured;
    private boolean isHotDeal;
    private UUID vendorId;
    private String vendorCompanyName;
    private boolean vendorVerified;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
