package com.landgo.coreservice.controller;

import com.landgo.coreservice.dto.request.ImageConfirmRequest;
import com.landgo.coreservice.dto.request.ImageUploadRequest;
import com.landgo.coreservice.dto.response.LandResponse;
import com.landgo.coreservice.dto.response.PresignedUrlResponse;
import com.landgo.coreservice.service.ImageStorageService;
import com.landgo.coreservice.service.LandService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.security.Principal;
import java.util.UUID;

@Slf4j
@RestController
@RequestMapping("/api/v1/listings/{id}")
@RequiredArgsConstructor
@Tag(name = "Land Media", description = "Endpoints for managing listing images and documents")
public class LandMediaController {

    private final ImageStorageService imageStorageService;
    private final LandService landService;

    // ==========================================
    // IMAGES
    // ==========================================

    @PostMapping("/images/presigned-url")
    @PreAuthorize("hasRole('VENDOR')")
    @Operation(summary = "Generate S3 presigned URL for direct image upload", security = @SecurityRequirement(name = "bearerAuth"))
    public ResponseEntity<PresignedUrlResponse> generateImagePresignedUrl(
            @PathVariable UUID id,
            @Valid @RequestBody ImageUploadRequest request,
            Principal principal) {
        
        String directory = "listings/" + id.toString() + "/images";
        PresignedUrlResponse response = imageStorageService.generatePresignedUrl(request, directory);
        return ResponseEntity.ok(response);
    }

    @PostMapping("/images/confirm")
    @PreAuthorize("hasRole('VENDOR')")
    @Operation(summary = "Confirm image upload and save metadata", security = @SecurityRequirement(name = "bearerAuth"))
    public ResponseEntity<LandResponse> confirmImageUpload(
            @PathVariable UUID id,
            @Valid @RequestBody ImageConfirmRequest request,
            Principal principal) {
        
        UUID vendorId = UUID.fromString(principal.getName());
        LandResponse response = landService.addImageMetadata(id, vendorId, request);
        return ResponseEntity.ok(response);
    }

    /**
     * Deletes one image.
     *
     * <p>The key is a query parameter, not a path segment: a file key looks like
     * {@code listings/<uuid>/images/<uuid>.jpg}, and its slashes meant the path-variable form
     * never matched — every delete came back 404 or 400 regardless of the key sent.
     */
    @DeleteMapping("/images")
    @PreAuthorize("hasRole('VENDOR')")
    @Operation(summary = "Delete an image from S3 and metadata", security = @SecurityRequirement(name = "bearerAuth"))
    public ResponseEntity<LandResponse> deleteImage(
            @PathVariable UUID id,
            @RequestParam String fileKey,
            Principal principal) {
        
        UUID vendorId = UUID.fromString(principal.getName());
        LandResponse response = landService.removeImageMetadata(id, vendorId, fileKey);
        imageStorageService.deleteImage(fileKey);
        return ResponseEntity.ok(response);
    }

    /**
     * Older path-variable form, kept so a deployed client is not broken by the move.
     *
     * <p>Only ever worked for a key with no slashes, which no key generated by this service has;
     * {@code /images/**} captures the rest of the path so at least those calls now resolve.
     */
    @DeleteMapping("/images/**")
    @PreAuthorize("hasRole('VENDOR')")
    @Operation(summary = "Delete an image by path (deprecated — use DELETE /images?fileKey=)",
            security = @SecurityRequirement(name = "bearerAuth"))
    public ResponseEntity<LandResponse> deleteImageByPath(
            @PathVariable UUID id,
            jakarta.servlet.http.HttpServletRequest request,
            Principal principal) {
        String fileKey = extractTrailingPath(request, "/images/");
        return deleteImage(id, fileKey, principal);
    }

    // ==========================================
    // DOCUMENTS
    // ==========================================

    @PostMapping("/documents/presigned-url")
    @PreAuthorize("hasRole('VENDOR')")
    @Operation(summary = "Generate S3 presigned URL for direct document upload", security = @SecurityRequirement(name = "bearerAuth"))
    public ResponseEntity<PresignedUrlResponse> generateDocumentPresignedUrl(
            @PathVariable UUID id,
            @Valid @RequestBody ImageUploadRequest request,
            Principal principal) {
        
        String directory = "listings/" + id.toString() + "/documents";
        PresignedUrlResponse response = imageStorageService.generatePresignedUrl(request, directory);
        return ResponseEntity.ok(response);
    }

    @PostMapping("/documents/confirm")
    @PreAuthorize("hasRole('VENDOR')")
    @Operation(summary = "Confirm document upload and save metadata", security = @SecurityRequirement(name = "bearerAuth"))
    public ResponseEntity<LandResponse> confirmDocumentUpload(
            @PathVariable UUID id,
            @Valid @RequestBody ImageConfirmRequest request,
            Principal principal) {
        
        UUID vendorId = UUID.fromString(principal.getName());
        LandResponse response = landService.addDocumentMetadata(id, vendorId, request);
        return ResponseEntity.ok(response);
    }

    /** Deletes one document. Key as a query parameter — see {@link #deleteImage}. */
    @DeleteMapping("/documents")
    @PreAuthorize("hasRole('VENDOR')")
    @Operation(summary = "Delete a document from S3 and metadata", security = @SecurityRequirement(name = "bearerAuth"))
    public ResponseEntity<LandResponse> deleteDocument(
            @PathVariable UUID id,
            @RequestParam String fileKey,
            Principal principal) {
        
        UUID vendorId = UUID.fromString(principal.getName());
        LandResponse response = landService.removeDocumentMetadata(id, vendorId, fileKey);
        imageStorageService.deleteImage(fileKey);
        return ResponseEntity.ok(response);
    }

    /** Older path-variable form, kept for deployed clients. */
    @DeleteMapping("/documents/**")
    @PreAuthorize("hasRole('VENDOR')")
    @Operation(summary = "Delete a document by path (deprecated — use DELETE /documents?fileKey=)",
            security = @SecurityRequirement(name = "bearerAuth"))
    public ResponseEntity<LandResponse> deleteDocumentByPath(
            @PathVariable UUID id,
            jakarta.servlet.http.HttpServletRequest request,
            Principal principal) {
        return deleteDocument(id, extractTrailingPath(request, "/documents/"), principal);
    }

    /**
     * Everything after {@code marker} in the request path, URL-decoded.
     *
     * <p>Spring's {@code @PathVariable} stops at the first slash, which is exactly what a file key
     * is full of, so the raw path is read instead.
     */
    private String extractTrailingPath(jakarta.servlet.http.HttpServletRequest request, String marker) {
        String path = request.getRequestURI();
        int index = path.indexOf(marker);
        if (index < 0) {
            throw new com.landgo.coreservice.exception.BadRequestException(
                    "fileKey is required", "VALIDATION_ERROR");
        }
        String raw = path.substring(index + marker.length());
        String key = java.net.URLDecoder.decode(raw, java.nio.charset.StandardCharsets.UTF_8);
        if (key.isBlank()) {
            throw new com.landgo.coreservice.exception.BadRequestException(
                    "fileKey is required", "VALIDATION_ERROR");
        }
        return key;
    }
}
